val str : string -> Document.t
val underscore : Document.t
val star : Document.t
val ampersand : Document.t
val tilde : Document.t
val qmark : Document.t
val dot : Document.t
val dothash : Document.t
val colon : Document.t
val semi : Document.t
val semisemi : Document.t
val comma : Document.t
val squote : Document.t
val dquote : Document.t
val bquote : Document.t
val lparen : Document.t
val rparen : Document.t
val lbracket : Document.t
val rbracket : Document.t
val lbrace : Document.t
val rbrace : Document.t
val bang : Document.t
val plus : Document.t
val minus : Document.t
val equals : Document.t
val to_ : Document.t
val downto_ : Document.t
val private_ : Document.t
val mutable_ : Document.t
val virtual_ : Document.t
val functor_ : Document.t
val rarrow : Document.t
val at : Document.t
val atat : Document.t
val lbracket_at : Document.t
val lbracket_atat : Document.t
val lbracket_atatat : Document.t
val lbracket_percent : Document.t
val lbracket_percentpercent : Document.t
val when_ : Document.t
val with_ : Document.t
val and_ : Document.t
val module_ : Document.t
val of_ : Document.t
val as_ : Document.t
val type_ : Document.t
val lazy_ : Document.t
val exception_ : Document.t
val let_ : Document.t
val rec_ : Document.t
val in_ : Document.t
val fun_ : Document.t
val function_ : Document.t
val match_ : Document.t
val try_ : Document.t
val if_ : Document.t
val then_ : Document.t
val else_ : Document.t
val while_ : Document.t
val do_ : Document.t
val done_ : Document.t
val for_ : Document.t
val assert_ : Document.t
val object_ : Document.t
val new_ : Document.t
val begin_ : Document.t
val end_ : Document.t
val struct_ : Document.t
val sig_ : Document.t
val stack__ : Document.t
val overwrite__ : Document.t
val constraint_ : Document.t
val coerce : Document.t
val larrow : Document.t
val colon_equals : Document.t
val plus_equals : Document.t
val dotdot : Document.t
val pipe : Document.t
val optional_pipe : Document.Condition.t -> Document.t
val open_ : Document.t
val inherit_ : Document.t
val val_ : Document.t
val method_ : Document.t
val initializer_ : Document.t
val nonrec_ : Document.t
val class_ : Document.t
val kind_abbrev__ : Document.t
val kind_of__ : Document.t
val include_ : Document.t
val mod_ : Document.t
val hash : Document.t
val hash_lparen : Document.t
val hash_lbrace : Document.t
val lt : Document.t
val gt : Document.t
val lbracket_gt : Document.t
val lbracket_lt : Document.t
val lbracket_colon : Document.t
val colon_rbracket : Document.t
val lbracket_pipe : Document.t
val pipe_rbracket : Document.t
val lbrace_lt : Document.t
val gt_rbrace : Document.t
val external_ : Document.t
val cons : Document.t
val exclave__ : Document.t
val global__ : Document.t
val lt_lbracket : Document.t
val rbracket_gt : Document.t
val dollar : Document.t
