(* Auto-generated by generate_typ.sh - do not hand-edit. *)

type t1
type t2
type ('a, 'b) pair

type t_arrow = (t1 -> t2) -> t2
type t_tuple = (t1 * t2) -> t2
type t_nested_constr = (t1 t2) -> t2
type t_pair_constr = ((t1, t2) pair) -> t2
