(* Auto-generated by generate.sh - do not hand-edit. *)

let a = 1
let b = 2
let c = 3
let x = 1
let y = 2
let z = 3
let f x = x
let h a b = ignore b; a
let g () = 1
let lab ~x = x
let rest = [ 1; 2; 3 ]
let aref = ref 1
type rec_t = { mutable fld : int }
let o = { fld = 1 }
let ( >>= ) m k = k m
let ( +++ ) x y = x + y
let ( <+> ) x y = x < y
class c = object
  method m = 1
end
let o2 = new c

let simple_if = assert ((if true then 1 else 2) = 1)
let simple_match = assert ((match y with 0 -> 1 | _ -> 2) = 1)
let simple_try = assert ((try g () with Not_found -> 1) = 1)
let simple_function = assert ((function 0 -> 1 | _ -> 2) = 1)
let simple_fun = assert ((fun z -> z + 1) = 1)
let simple_let = assert ((let w = 1 in w + 1) = 1)
let simple_seq = assert ((a; b) = 1)
let simple_tuple = assert ((1, 2) = 1)
let plain_infix = assert ((1 + 2) = 1)
let mixed_infix = assert ((1 * 2 + 3) = 1)
let infix_then_function = assert ((g >>= function 0 -> 1 | _ -> 2) = 1)
let let_module = assert ((let module M = struct end in 1) = 1)
let let_exception = assert ((let exception Foo in 1) = 1)
