(* Auto-generated by generate_pat.sh - do not hand-edit. *)

type t = A of int | B of int
type t_wrap = A_wrap of t

let f_alias = function A_wrap (x as n) -> 0 | _ -> 1
let f_or = function A_wrap (A _ | B _) -> 0 | _ -> 1
let f_tuple = function A_wrap (x, y) -> 0 | _ -> 1
let f_cons = function A_wrap (x :: y) -> 0 | _ -> 1
let f_nested_construct = function A_wrap (A n) -> 0 | _ -> 1
let f_lazy_pat = function A_wrap (lazy n) -> 0 | _ -> 1
