(* Auto-generated by generate_pat.sh - do not hand-edit. *)

type t = A of int | B of int
type t_wrap = A_wrap of t

let f_alias = function x :: (x as n) -> 0 | _ -> 1
let f_or = function x :: (A _ | B _) -> 0 | _ -> 1
let f_tuple = function x :: (x, y) -> 0 | _ -> 1
let f_cons = function x :: (x :: y) -> 0 | _ -> 1
let f_nested_construct = function x :: (A n) -> 0 | _ -> 1
let f_lazy_pat = function x :: (lazy n) -> 0 | _ -> 1
