(* Auto-generated by generate.sh - do not hand-edit. *)

let a = 1
let b = 2
let c = 3
let x = 1
let y = 2
let z = 3
let f x = x
let h a b = ignore b; a
let g () = 1
let lab ~x = x
let rest = [ 1; 2; 3 ]
let aref = ref 1
type rec_t = { mutable fld : int }
let o = { fld = 1 }
let ( >>= ) m k = k m
let ( +++ ) x y = x + y
let ( <+> ) x y = x < y
class c = object
  method m = 1
end
let o2 = new c

let simple_if = for i = 0 to (if true then 1 else 2) do () done
let simple_match = for i = 0 to (match y with 0 -> 1 | _ -> 2) do () done
let simple_try = for i = 0 to (try g () with Not_found -> 1) do () done
let simple_function = for i = 0 to (function 0 -> 1 | _ -> 2) do () done
let simple_fun = for i = 0 to (fun z -> z + 1) do () done
let simple_let = for i = 0 to (let w = 1 in w + 1) do () done
let simple_seq = for i = 0 to (a; b) do () done
let simple_tuple = for i = 0 to (1, 2) do () done
let plain_infix = for i = 0 to (1 + 2) do () done
let mixed_infix = for i = 0 to (1 * 2 + 3) do () done
let infix_then_function = for i = 0 to (g >>= function 0 -> 1 | _ -> 2) do () done
let let_module = for i = 0 to (let module M = struct end in 1) do () done
let let_exception = for i = 0 to (let exception Foo in 1) do () done
