(* Auto-generated by generate.sh - do not hand-edit. *)

let a = 1
let b = 2
let c = 3
let x = 1
let y = 2
let z = 3
let f x = x
let h a b = ignore b; a
let g () = 1
let lab ~x = x
let rest = [ 1; 2; 3 ]
let aref = ref 1
type rec_t = { mutable fld : int }
let o = { fld = 1 }
let ( >>= ) m k = k m
let ( +++ ) x y = x + y
let ( <+> ) x y = x < y
class c = object
  method m = 1
end
let o2 = new c

let simple_if = for i = 0 to 10 do (if true then 1 else 2) done
let simple_match = for i = 0 to 10 do (match y with 0 -> 1 | _ -> 2) done
let simple_try = for i = 0 to 10 do (try g () with Not_found -> 1) done
let simple_function = for i = 0 to 10 do (function 0 -> 1 | _ -> 2) done
let simple_fun = for i = 0 to 10 do (fun z -> z + 1) done
let simple_let = for i = 0 to 10 do (let w = 1 in w + 1) done
let simple_seq = for i = 0 to 10 do (a; b) done
let simple_tuple = for i = 0 to 10 do (1, 2) done
let plain_infix = for i = 0 to 10 do (1 + 2) done
let mixed_infix = for i = 0 to 10 do (1 * 2 + 3) done
let infix_then_function = for i = 0 to 10 do (g >>= function 0 -> 1 | _ -> 2) done
let let_module = for i = 0 to 10 do (let module M = struct end in 1) done
let let_exception = for i = 0 to 10 do (let exception Foo in 1) done
