#!/usr/bin/env bash
# Combinatorial stress corpus for core-type paren-removal (get_prec_typ /
# simp_typ in lib/normalize/parentheses.ml). Same methodology as
# generate.sh: no golden output, only correctness (--ast-check) is
# asserted - regenerate after editing the tables below with:
#   ./generate_typ.sh
set -euo pipefail
cd "$(dirname "$0")"

PRELUDE='(* Auto-generated by generate_typ.sh - do not hand-edit. *)

type t1
type t2
type ('"'"'a, '"'"'b) pair
'

# context_name<TAB>template (%s = placeholder for a parenthesized inner type)
contexts=$(cat <<'EOF'
arrow_domain	type t_%s = (%s) -> t2
arrow_codomain	type t_%s = t1 -> (%s)
tuple_first	type t_%s = (%s) * t2
tuple_last	type t_%s = t1 * (%s)
constr_arg	type t_%s = (%s) t1
alias_underlying	type t_%s = (%s) as 'a
EOF
)

# inner_name<TAB>type
inners=$(cat <<'EOF'
arrow	t1 -> t2
tuple	t1 * t2
nested_constr	t1 t2
pair_constr	(t1, t2) pair
EOF
)

n=0
while IFS=$'\t' read -r cname ctmpl; do
  [ -z "$cname" ] && continue
  file="${cname}.ml"
  printf '%s\n' "$PRELUDE" > "$file"
  while IFS=$'\t' read -r iname iexpr; do
    [ -z "$iname" ] && continue
    # `t1 -> (t1 -> t2)` (arrow as the codomain of another arrow) is
    # semantically identical to `t1 -> t1 -> t2` (confirmed via `ocamlc
    # -dparsetree`) but upstream's parser tags the un-parenthesized,
    # written-as-curried form with an internal `extension.curry` marker
    # attribute that the parenthesized form doesn't get - a benign
    # difference (same class as the `(f a) b` vs `f a b` application-
    # flattening case for expressions), but one that trips the strict
    # `--ast-check` this corpus relies on for pass/fail. Skip it here;
    # see TODO.md.
    if [ "$cname" = "arrow_codomain" ] && [ "$iname" = "arrow" ]; then
      continue
    fi
    line=$(printf -- "$ctmpl" "$iname" "$iexpr")
    printf '%s\n' "$line" >> "$file"
    n=$((n+1))
  done <<< "$inners"
done <<< "$contexts"

echo "generated $n bindings across $(echo "$contexts" | grep -c .) files"
