#!/usr/bin/env bash
# Regenerates the *.ml files in this directory: a combinatorial stress
# corpus for `--remove-parentheses` (lib/normalize/parentheses.ml), the pass
# that strips redundant parentheses from expressions.
#
# For each (syntactic CONTEXT, "risky" INNER expression) pair, this embeds
# the inner expression - explicitly parenthesized - into that context, as
# one binding in the context's file. There is no golden/expected output:
# the only thing under test is CORRECTNESS - `PARENT=remove style
# --ast-check --idempotence-check`, wired up by gen-dune.sh, fails loudly
# if the remover ever strips parentheses that change the parsed meaning.
# Whether the remover actually strips a given REDUNDANT pair of parens is
# not checked here (that's what test/parentheses-gallery/ is for, with
# golden files); this corpus exists purely to catch NECESSARY parens being
# wrongly removed, across many more combinations than anyone would want to
# hand-verify.
#
# Regenerate after editing the $contexts/$inners tables below:
#   ./generate.sh
set -euo pipefail
cd "$(dirname "$0")"
rm -f *.ml

PRELUDE='(* Auto-generated by generate.sh - do not hand-edit. *)

let a = 1
let b = 2
let c = 3
let x = 1
let y = 2
let z = 3
let f x = x
let h a b = ignore b; a
let g () = 1
let lab ~x = x
let rest = [ 1; 2; 3 ]
let aref = ref 1
type rec_t = { mutable fld : int }
let o = { fld = 1 }
let ( >>= ) m k = k m
let ( +++ ) x y = x + y
let ( <+> ) x y = x < y
class c = object
  method m = 1
end
let o2 = new c
'

# context_name<TAB>template (with %s as the placeholder for a parenthesized
# inner expression)
contexts=$(cat <<'EOF'
infix_left_plus	(%s) + b
infix_right_plus	a + (%s)
infix_left_star	(%s) * b
infix_right_star	a * (%s)
infix_left_and	(%s) && true
infix_right_and	true && (%s)
infix_left_or	(%s) || true
infix_right_or	true || (%s)
infix_left_pow	(%s) ** a
infix_right_pow	a ** (%s)
infix_right_caret	"s" ^ (%s)
infix_right_at	rest @ (%s)
infix_left_cmp	((%s)) < 1
infix_right_cmp	1 < (%s)
infix_right_custom	a +++ (%s)
infix_right_custom_cmp	a <+> (%s)
cons_left	(%s) :: rest
cons_right	x :: (%s)
unary_minus	- (%s)
app_fun_pos	(%s) a
app_arg_first	f (%s)
app_arg_second	h (%s) a
labeled_arg	lab ~x:(%s)
tuple_first	(%s), b
tuple_last	a, (%s)
tuple_mid	a, (%s), c
constructor_arg	Some (%s)
constructor_two_levels	Some (Some (%s))
field_base	(%s).fld
record_field_value	{ fld = (%s) }
array_elt	[| (%s); 1 |]
list_elt	[ (%s); 1 ]
if_cond	if (%s) then a else b
if_then_noelse	if true then (%s)
if_then_withelse	if true then (%s) else b
if_else	if true then a else (%s)
seq_first	(%s); b
seq_last	a; (%s)
match_scrutinee	match (%s) with 0 -> a | _ -> b
match_last_case	match x with 0 -> a | _ -> (%s)
match_nonlast_case	match x with 0 -> (%s) | _ -> b
match_nonlast_case_of_3	match x with 0 -> (%s) | 1 -> b | _ -> c
function_last_case	(function 0 -> a | _ -> (%s))
function_nonlast_case	(function 0 -> (%s) | _ -> b)
try_last_case	try g () with Not_found -> (%s)
try_nonlast_case	try g () with Not_found -> (%s) | _ -> b
let_body	let w = 1 in (%s)
let_binding_rhs	(%s)
assign_rhs	aref := (%s)
setfield_rhs	o.fld <- (%s)
index_assign_rhs	rest.(0) <- (%s)
nested_match_in_if_then	if true then (match y with 0 -> (%s) | _ -> 2) else 3
nested_if_in_match_nonlast	match x with 0 -> (if true then (%s) else 2) | _ -> 3
nested_match_in_match_last	match x with 0 -> a | _ -> (match y with 0 -> (%s) | _ -> 2)
nested_match_in_match_nonlast	match x with 0 -> (match y with 0 -> (%s) | _ -> 2) | _ -> b
nested_deep_infix_seqfirst	((%s) + 1); b
nested_infix_then_seq	a + ((%s); b)
assert_arg	assert ((%s) = 1)
lazy_arg	lazy (%s)
while_cond	while (%s) do () done
while_body	while true do (%s) done
for_from	for i = (%s) to 10 do () done
for_to	for i = 0 to (%s) do () done
for_body	for i = 0 to 10 do (%s) done
coerce_lhs	((%s) :> int)
constraint_lhs	((%s) : int)
send_receiver	(%s)#m
EOF
)

# inner_name<TAB>expr
inners=$(cat <<'EOF'
simple_if	if true then 1 else 2
simple_match	match y with 0 -> 1 | _ -> 2
simple_try	try g () with Not_found -> 1
simple_function	function 0 -> 1 | _ -> 2
simple_fun	fun z -> z + 1
simple_let	let w = 1 in w + 1
simple_seq	a; b
simple_tuple	1, 2
plain_infix	1 + 2
mixed_infix	1 * 2 + 3
infix_then_function	g >>= function 0 -> 1 | _ -> 2
let_module	let module M = struct end in 1
let_exception	let exception Foo in 1
EOF
)

n=0
while IFS=$'\t' read -r cname ctmpl; do
  [ -z "$cname" ] && continue
  file="${cname}.ml"
  printf '%s\n' "$PRELUDE" > "$file"
  while IFS=$'\t' read -r iname iexpr; do
    [ -z "$iname" ] && continue
    body=$(printf -- "$ctmpl" "$iexpr")
    printf 'let %s = %s\n' "$iname" "$body" >> "$file"
    n=$((n+1))
  done <<< "$inners"
done <<< "$contexts"

echo "generated $n bindings across $(echo "$contexts" | grep -c .) files"
