#!/usr/bin/env bash
# Combinatorial stress corpus for pattern paren-removal (get_prec_pat /
# simp_pat in lib/normalize/parentheses.ml). Same methodology as
# generate.sh: no golden output, only correctness (--ast-check) is
# asserted - regenerate after editing the tables below with:
#   ./generate_pat.sh
set -euo pipefail
cd "$(dirname "$0")"

PRELUDE='(* Auto-generated by generate_pat.sh - do not hand-edit. *)

type t = A of int | B of int
type t_wrap = A_wrap of t
'

# context_name<TAB>template (%s = placeholder for a parenthesized inner pattern)
contexts=$(cat <<'EOF'
or_left	let f_%s = function (%s) | B _ -> 0 | _ -> 1
or_right	let f_%s = function A _ | (%s) -> 0 | _ -> 1
tuple_first	let f_%s = function (%s), y -> 0 | _ -> 1
tuple_last	let f_%s = function x, (%s) -> 0 | _ -> 1
cons_head	let f_%s = function (%s) :: rest -> 0 | _ -> 1
cons_tail	let f_%s = function x :: (%s) -> 0 | _ -> 1
construct_arg	let f_%s = function A_wrap (%s) -> 0 | _ -> 1
lazy_arg	let f_%s = function lazy (%s) -> 0 | _ -> 1
alias_pat	let f_%s = function (%s) as p -> ignore p; 0 | _ -> 1
EOF
)

# inner_name<TAB>pattern
inners=$(cat <<'EOF'
alias	x as n
or	A _ | B _
tuple	x, y
cons	x :: y
nested_construct	A n
lazy_pat	lazy n
EOF
)

n=0
while IFS=$'\t' read -r cname ctmpl; do
  [ -z "$cname" ] && continue
  file="${cname}.ml"
  printf '%s\n' "$PRELUDE" > "$file"
  while IFS=$'\t' read -r iname iexpr; do
    [ -z "$iname" ] && continue
    line=$(printf -- "$ctmpl" "$iname" "$iexpr")
    printf '%s\n' "$line" >> "$file"
    n=$((n+1))
  done <<< "$inners"
done <<< "$contexts"

echo "generated $n bindings across $(echo "$contexts" | grep -c .) files"
