(* Auto-generated by generate.sh - do not hand-edit. *)

let a = 1
let b = 2
let c = 3
let x = 1
let y = 2
let z = 3
let f x = x
let h a b = ignore b; a
let g () = 1
let lab ~x = x
let rest = [ 1; 2; 3 ]
let aref = ref 1
type rec_t = { mutable fld : int }
let o = { fld = 1 }
let ( >>= ) m k = k m
let ( +++ ) x y = x + y
let ( <+> ) x y = x < y
class c = object
  method m = 1
end
let o2 = new c

let simple_if = "s" ^ (if true then 1 else 2)
let simple_match = "s" ^ (match y with 0 -> 1 | _ -> 2)
let simple_try = "s" ^ (try g () with Not_found -> 1)
let simple_function = "s" ^ (function 0 -> 1 | _ -> 2)
let simple_fun = "s" ^ (fun z -> z + 1)
let simple_let = "s" ^ (let w = 1 in w + 1)
let simple_seq = "s" ^ (a; b)
let simple_tuple = "s" ^ (1, 2)
let plain_infix = "s" ^ (1 + 2)
let mixed_infix = "s" ^ (1 * 2 + 3)
let infix_then_function = "s" ^ (g >>= function 0 -> 1 | _ -> 2)
let let_module = "s" ^ (let module M = struct end in 1)
let let_exception = "s" ^ (let exception Foo in 1)
