(* Auto-generated by generate.sh - do not hand-edit. *)

let a = 1
let b = 2
let c = 3
let x = 1
let y = 2
let z = 3
let f x = x
let h a b = ignore b; a
let g () = 1
let lab ~x = x
let rest = [ 1; 2; 3 ]
let aref = ref 1
type rec_t = { mutable fld : int }
let o = { fld = 1 }
let ( >>= ) m k = k m
let ( +++ ) x y = x + y
let ( <+> ) x y = x < y
class c = object
  method m = 1
end
let o2 = new c

let simple_if = (if true then 1 else 2) + b
let simple_match = (match y with 0 -> 1 | _ -> 2) + b
let simple_try = (try g () with Not_found -> 1) + b
let simple_function = (function 0 -> 1 | _ -> 2) + b
let simple_fun = (fun z -> z + 1) + b
let simple_let = (let w = 1 in w + 1) + b
let simple_seq = (a; b) + b
let simple_tuple = (1, 2) + b
let plain_infix = (1 + 2) + b
let mixed_infix = (1 * 2 + 3) + b
let infix_then_function = (g >>= function 0 -> 1 | _ -> 2) + b
let let_module = (let module M = struct end in 1) + b
let let_exception = (let exception Foo in 1) + b
