(* Auto-generated by generate_pat.sh - do not hand-edit. *)

type t = A of int | B of int
type t_wrap = A_wrap of t

let f_alias = function lazy (x as n) -> 0 | _ -> 1
let f_or = function lazy (A _ | B _) -> 0 | _ -> 1
let f_tuple = function lazy (x, y) -> 0 | _ -> 1
let f_cons = function lazy (x :: y) -> 0 | _ -> 1
let f_nested_construct = function lazy (A n) -> 0 | _ -> 1
let f_lazy_pat = function lazy (lazy n) -> 0 | _ -> 1
