(* Auto-generated by generate.sh - do not hand-edit. *)

let a = 1
let b = 2
let c = 3
let x = 1
let y = 2
let z = 3
let f x = x
let h a b = ignore b; a
let g () = 1
let lab ~x = x
let rest = [ 1; 2; 3 ]
let aref = ref 1
type rec_t = { mutable fld : int }
let o = { fld = 1 }
let ( >>= ) m k = k m
let ( +++ ) x y = x + y
let ( <+> ) x y = x < y
class c = object
  method m = 1
end
let o2 = new c

let simple_if = let w = 1 in (if true then 1 else 2)
let simple_match = let w = 1 in (match y with 0 -> 1 | _ -> 2)
let simple_try = let w = 1 in (try g () with Not_found -> 1)
let simple_function = let w = 1 in (function 0 -> 1 | _ -> 2)
let simple_fun = let w = 1 in (fun z -> z + 1)
let simple_let = let w = 1 in (let w = 1 in w + 1)
let simple_seq = let w = 1 in (a; b)
let simple_tuple = let w = 1 in (1, 2)
let plain_infix = let w = 1 in (1 + 2)
let mixed_infix = let w = 1 in (1 * 2 + 3)
let infix_then_function = let w = 1 in (g >>= function 0 -> 1 | _ -> 2)
let let_module = let w = 1 in (let module M = struct end in 1)
let let_exception = let w = 1 in (let exception Foo in 1)
