(* Auto-generated by generate.sh - do not hand-edit. *)

let a = 1
let b = 2
let c = 3
let x = 1
let y = 2
let z = 3
let f x = x
let h a b = ignore b; a
let g () = 1
let lab ~x = x
let rest = [ 1; 2; 3 ]
let aref = ref 1
type rec_t = { mutable fld : int }
let o = { fld = 1 }
let ( >>= ) m k = k m
let ( +++ ) x y = x + y
let ( <+> ) x y = x < y
class c = object
  method m = 1
end
let o2 = new c

let simple_if = match (if true then 1 else 2) with 0 -> a | _ -> b
let simple_match = match (match y with 0 -> 1 | _ -> 2) with 0 -> a | _ -> b
let simple_try = match (try g () with Not_found -> 1) with 0 -> a | _ -> b
let simple_function = match (function 0 -> 1 | _ -> 2) with 0 -> a | _ -> b
let simple_fun = match (fun z -> z + 1) with 0 -> a | _ -> b
let simple_let = match (let w = 1 in w + 1) with 0 -> a | _ -> b
let simple_seq = match (a; b) with 0 -> a | _ -> b
let simple_tuple = match (1, 2) with 0 -> a | _ -> b
let plain_infix = match (1 + 2) with 0 -> a | _ -> b
let mixed_infix = match (1 * 2 + 3) with 0 -> a | _ -> b
let infix_then_function = match (g >>= function 0 -> 1 | _ -> 2) with 0 -> a | _ -> b
let let_module = match (let module M = struct end in 1) with 0 -> a | _ -> b
let let_exception = match (let exception Foo in 1) with 0 -> a | _ -> b
