(* Auto-generated by generate.sh - do not hand-edit. *)

let a = 1
let b = 2
let c = 3
let x = 1
let y = 2
let z = 3
let f x = x
let h a b = ignore b; a
let g () = 1
let lab ~x = x
let rest = [ 1; 2; 3 ]
let aref = ref 1
type rec_t = { mutable fld : int }
let o = { fld = 1 }
let ( >>= ) m k = k m
let ( +++ ) x y = x + y
let ( <+> ) x y = x < y
class c = object
  method m = 1
end
let o2 = new c

let simple_if = if true then (match y with 0 -> (if true then 1 else 2) | _ -> 2) else 3
let simple_match = if true then (match y with 0 -> (match y with 0 -> 1 | _ -> 2) | _ -> 2) else 3
let simple_try = if true then (match y with 0 -> (try g () with Not_found -> 1) | _ -> 2) else 3
let simple_function = if true then (match y with 0 -> (function 0 -> 1 | _ -> 2) | _ -> 2) else 3
let simple_fun = if true then (match y with 0 -> (fun z -> z + 1) | _ -> 2) else 3
let simple_let = if true then (match y with 0 -> (let w = 1 in w + 1) | _ -> 2) else 3
let simple_seq = if true then (match y with 0 -> (a; b) | _ -> 2) else 3
let simple_tuple = if true then (match y with 0 -> (1, 2) | _ -> 2) else 3
let plain_infix = if true then (match y with 0 -> (1 + 2) | _ -> 2) else 3
let mixed_infix = if true then (match y with 0 -> (1 * 2 + 3) | _ -> 2) else 3
let infix_then_function = if true then (match y with 0 -> (g >>= function 0 -> 1 | _ -> 2) | _ -> 2) else 3
let let_module = if true then (match y with 0 -> (let module M = struct end in 1) | _ -> 2) else 3
let let_exception = if true then (match y with 0 -> (let exception Foo in 1) | _ -> 2) else 3
