(* Auto-generated by generate_pat.sh - do not hand-edit. *)

type t = A of int | B of int
type t_wrap = A_wrap of t

let f_alias = function (x as n) | B _ -> 0 | _ -> 1
let f_or = function (A _ | B _) | B _ -> 0 | _ -> 1
let f_tuple = function (x, y) | B _ -> 0 | _ -> 1
let f_cons = function (x :: y) | B _ -> 0 | _ -> 1
let f_nested_construct = function (A n) | B _ -> 0 | _ -> 1
let f_lazy_pat = function (lazy n) | B _ -> 0 | _ -> 1
