(* Auto-generated by generate.sh - do not hand-edit. *)

let a = 1
let b = 2
let c = 3
let x = 1
let y = 2
let z = 3
let f x = x
let h a b = ignore b; a
let g () = 1
let lab ~x = x
let rest = [ 1; 2; 3 ]
let aref = ref 1
type rec_t = { mutable fld : int }
let o = { fld = 1 }
let ( >>= ) m k = k m
let ( +++ ) x y = x + y
let ( <+> ) x y = x < y
class c = object
  method m = 1
end
let o2 = new c

let simple_if = o.fld <- (if true then 1 else 2)
let simple_match = o.fld <- (match y with 0 -> 1 | _ -> 2)
let simple_try = o.fld <- (try g () with Not_found -> 1)
let simple_function = o.fld <- (function 0 -> 1 | _ -> 2)
let simple_fun = o.fld <- (fun z -> z + 1)
let simple_let = o.fld <- (let w = 1 in w + 1)
let simple_seq = o.fld <- (a; b)
let simple_tuple = o.fld <- (1, 2)
let plain_infix = o.fld <- (1 + 2)
let mixed_infix = o.fld <- (1 * 2 + 3)
let infix_then_function = o.fld <- (g >>= function 0 -> 1 | _ -> 2)
let let_module = o.fld <- (let module M = struct end in 1)
let let_exception = o.fld <- (let exception Foo in 1)
