(* Auto-generated by generate.sh - do not hand-edit. *)

let a = 1
let b = 2
let c = 3
let x = 1
let y = 2
let z = 3
let f x = x
let h a b = ignore b; a
let g () = 1
let lab ~x = x
let rest = [ 1; 2; 3 ]
let aref = ref 1
type rec_t = { mutable fld : int }
let o = { fld = 1 }
let ( >>= ) m k = k m
let ( +++ ) x y = x + y
let ( <+> ) x y = x < y
class c = object
  method m = 1
end
let o2 = new c

let simple_if = while (if true then 1 else 2) do () done
let simple_match = while (match y with 0 -> 1 | _ -> 2) do () done
let simple_try = while (try g () with Not_found -> 1) do () done
let simple_function = while (function 0 -> 1 | _ -> 2) do () done
let simple_fun = while (fun z -> z + 1) do () done
let simple_let = while (let w = 1 in w + 1) do () done
let simple_seq = while (a; b) do () done
let simple_tuple = while (1, 2) do () done
let plain_infix = while (1 + 2) do () done
let mixed_infix = while (1 * 2 + 3) do () done
let infix_then_function = while (g >>= function 0 -> 1 | _ -> 2) do () done
let let_module = while (let module M = struct end in 1) do () done
let let_exception = while (let exception Foo in 1) do () done
